let one =document.getElementById("li_1");
let two =document.getElementById("li_2");
let  three =document.getElementById("li_3");
let four =document.getElementById("li_4");
let five =document.getElementById("li_5");
one.onclick =function(){}
two.onclick =function(){}
three.onclick =function(){}
four.onclick =function(){}
five.onclick =function(){}